In [1]:

# a=np.array([1,2,3,4,5,6],[2,3,4,5])
# print(a)

TypeError: Field elements must be 2- or 3-tuples, got '2'

In [3]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
c = np.zeros([3, 3])
c

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
# n1=np.full((30,30),55)
# # 

In [7]:
# n1

array([[55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55,
        55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55],
       [55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55,
        55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55],
       [55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55,
        55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55],
       [55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55,
        55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55],
       [55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55,
        55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55],
       [55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55,
        55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55],
       [55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55,
        55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55, 55],
       [55, 55, 55, 55, 55, 55, 55, 55, 5

In [11]:
# n2=np.arange(50,101)
# n2


array([ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
        63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
        76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
        89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [12]:
# n1=np.arange(50,500,10)
# n1

array([ 50,  60,  70,  80,  90, 100, 110, 120, 130, 140, 150, 160, 170,
       180, 190, 200, 210, 220, 230, 240, 250, 260, 270, 280, 290, 300,
       310, 320, 330, 340, 350, 360, 370, 380, 390, 400, 410, 420, 430,
       440, 450, 460, 470, 480, 490])

In [15]:
n4=np.random.randint(100,200,10)
n4

array([147, 184, 168, 123, 105, 138, 126, 104, 136, 190])

In [16]:
n5=np.array([[1,2,3,4],[4,3,2,1]])
n5

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [18]:
n5.shape=(8,1)
n5

array([[1],
       [2],
       [3],
       [4],
       [4],
       [3],
       [2],
       [1]])

In [19]:
n6=np.array([1,2,3])


In [20]:
n7=np.array([4,5,6])

In [21]:
np.vstack((n6,n7))

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
np.hstack((n6,n7))

array([1, 2, 3, 4, 5, 6])

In [23]:
#numpy
n1=np.array([10,20,30,40,50,60])

In [24]:
n2=np.array([50,60,70,80,90])

In [28]:
np.intersect1d(n1,n2)

array([ 50,  60,  70,  80,  90, 100])

In [30]:
np.setdiff1d(n1,n2)

array([110, 120, 130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230,
       240, 250, 260, 270, 280, 290, 300, 310, 320, 330, 340, 350, 360,
       370, 380, 390, 400, 410, 420, 430, 440, 450, 460, 470, 480, 490])

In [1]:
np.setdiff1d(n1,n2)

NameError: name 'np' is not defined

In [4]:
import numpy as np
n9=np.array([10,20,30])

In [5]:
n9-5


array([ 5, 15, 25])

In [6]:
n9*10

array([100, 200, 300])

In [7]:
n9/10

array([1., 2., 3.])

In [8]:
n11=np.random.randint(1,50,10)

In [9]:
n11

array([43, 31,  1, 49, 46, 41,  9, 38, 27, 24])

In [15]:
n12=np.array([1,2,3,4,5,6,7,8])

In [16]:
np.save('my_numpyy',n12)

In [12]:
n2=np.load('my_numpyy,npy')
n2

FileNotFoundError: [Errno 2] No such file or directory: 'my_numpy,npy'

AttributeError: module 'numpy' has no attribute 'aaray'